name: Build, Deploy

on:
  push:
    branches:
      - master

jobs:
  build-obfuscate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install axios @actions/core @actions/github javascript-obfuscator simple-git
        
      - name: Install dev dependencies
        run: npm install prettier --save-dev

      - name: build and push
        run: node ./.github/actions/gh-pages.js
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OWNER: Ajayos
          REPO: keerthana-plugins
          INPUT_BRANCH_NAME: gh-pages
